### ISSUE TITLE
Fails to use proton as runner.

### ISSUE THREAD

**Issue by LinoBigatti** [derrod/legendary#107]
Legendary fails to launch Watch Dogs 2 with proton 5.0, access denied.

Command output:
```
[13:42]lino@arch:~ $ legendary launch Angelonia
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Angelonia...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.1', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 1284, in main
    cli.launch_game(args, extra)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 511, in launch_game
    subprocess.Popen(params, cwd=cwd, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/lino/.steam/steam/steamapps/common/Proton 5.0/'
```

Config file:
```
[Legendary]
install_dir = /home/lino/CrossData/legendary


[Angelonia]
; Use a wrapper to run this script
; Note that the path might have to be quoted if it contains spaces
wrapper = "/home/lino/.steam/steam/steamapps/common/Proton 5.0/" run
; Do not run this executable with WINE (e.g. when the wrapper handles that)
no_wine = true
```

File permissions:
```
[13:49]lino@arch:common $ ls -l
total 4
drwxrwxrwx 4 lino lino 4096 Sep 26 15:16 'Proton 5.0'
```

System info:
```
OS: Arch Linux x86_64 
Host: H61H2-MV 1.0 
Kernel: 5.8.10-arch1-1 
Shell: bash 5.0.18 
CPU: Intel Celeron G1620 (2) @ 2.700GHz 
GPU: NVIDIA GeForce GT 710 
Memory: 1767MiB / 3883MiB 
```

Legendary status:
```
[13:50]lino@arch:~ $ legendary status
[Core] INFO: Trying to re-use existing login session...
Epic account: LinoBigatti
Games available: 26
Games installed: 2
EGL Sync enabled: False
Config directory: /home/lino/.config/legendary
```

**Comment by CommandMC** [comment]
Your `wrapper` has to be ` "/home/lino/.steam/steam/steamapps/common/Proton 5.0/proton" run`.

Not sure if this works though, I use just `"path/to/Proton 5.0/proton"` as my wrapper and `run` as my wine version

**Comment by LinoBigatti** [comment]
that did the trick with proton path, but now it has the following output:
```
[14:38]lino@arch:~ $ legendary launch Angelonia
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Angelonia...
Proton: No compat data path?
```

How do I config this?

**Comment by CommandMC** [comment]
You have to set a `STEAM_COMPAT_DATA_PATH` variable, which is essentially the proton equivalent of a wineprefix (they're not interchangeable though, proton creates a "pfx" directory inside the path specified which is your wine prefix)
