### ISSUE TITLE
Attempting list games

### ISSUE THREAD

**Issue by DeFynation** [derrod/legendary#120]
phial@phial:~/Downloads/legendary$ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[Core] WARNING: Resuming failed for unknown reason: ConnectionError(ProtocolError('Connection aborted.', OSError(0, 'Error')))
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f86d1c71970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f86d1c71970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.1', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/cli.py", line 1280, in main
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/cli.py", line 141, in list_games
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/core.py", line 181, in login
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/api/egs.py", line 67, in start_session
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f86d1c71970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by derrod** [comment]
Your nameservers don't seem to work correctly. This is not an issue with legendary itself.

Try pinging `account-public-service-prod03.ol.epicgames.com` and see what happens.
