### ISSUE TITLE
MemoryError: Current shared memory cache is smaller than required!

### ISSUE THREAD

**Issue by jonasW3F** [derrod/legendary#149]
I am trying to install Pillars of Eternity and I get a memory error. The weird thing is, that even after increasing the memory in the config, I receive the error.

`Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.4', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/cli.py", line 1325, in main
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/cli.py", line 594, in install_game
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/core.py", line 801, in prepare_download
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/downloader/manager.py", line 376, in run_analysis
MemoryError: Current shared memory cache is smaller than required! 23356.0 MiB < 23385.0 MiB. Try running legendary with the --enable-reordering flag to reduce memory usage.
`

**Comment by jonasW3F** [comment]
nvm I am stupid, I did not increase it enough.

**Comment by derrod** [comment]
Also see https://github.com/derrod/legendary/issues/17#issuecomment-743701890
