### ISSUE TITLE
Problems launching Pillars of Eternity

### ISSUE THREAD

**Issue by jonasW3F** [derrod/legendary#150]
After several attempts, I managed to install PoE. Now, when I want to run it, I receive an error:

legendary launch bcc75c246fe04e45b0c1f1c3fd52503a                                                                                 
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching bcc75c246fe04e45b0c1f1c3fd52503a...
[cli] DEBUG: Launch parameters: wine /home/MYPATH/PillarsOfEternity/win/PillarsofEternity.exe -AUTH_LOGIN=unused -AUTH_PASSWORD=MYPASSWORT -AUTH_TYPE=exchangecode -epicapp=bcc75c246fe04e45b0c1f1c3fd52503a -epicenv=Prod -EpicPortal -epicusername=MYNAME -epicuserid=MYID -epiclocale=en
[cli] DEBUG: Working directory: /home/MYPATH/PillarsOfEternity/win
[cli] DEBUG: Environment overrides:
Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.4', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/cli.py", line 1323, in main
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.4-py3.8.egg/legendary/cli.py", line 512, in launch_game
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1624, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/lib/python3.8/os.py", line 806, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by jonasW3F** [comment]
In order to install the game I had to increase the max_memory and copied the content of the config.ini from this repository. This seems to have created the issue when trying to run it. I fixed it by removing `rm -r ~/.config/legendary/config.ini` and launched the game again.
