### ISSUE TITLE
Can't install Pillars of Eternity: shared memory cache too small

### ISSUE THREAD

**Issue by delentef** [derrod/legendary#151]
Hello,

I am on Fedora 32 and I installed legendary version "0.20.3", codename "Point Insertion".

I authenticated and I listed my games. For Pillars of Eternity I got this:

```
 * Pillars of Eternity - Definitive Edition (App name: bcc75c246fe04e45b0c1f1c3fd52503a | Version: 1.0.2)
  + Pillars of Eternity - Definitive Edition Pack (App name: 8e975c15166a4a1ca28d65fdfa411248 | Version: 1.0.0)

```

Then I proceeded to install it with `legendary install 36b0e40890f147fbb1e3965f87369156` but it gave me this error:

```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /home/fab/legendary/PillarsOfEternity
Traceback (most recent call last):
  File "/usr/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.3', 'console_scripts', 'legendary')()
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 1313, in main
    cli.install_game(args)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 582, in install_game
    dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 806, in prepare_download
    anlres = dlm.run_analysis(manifest=new_manifest, old_manifest=old_manifest,
  File "/usr/lib/python3.8/site-packages/legendary/downloader/manager.py", line 375, in run_analysis
    raise MemoryError(f'Current shared memory cache is smaller than required! {shared_mib} < {required_mib}. '
MemoryError: Current shared memory cache is smaller than required! 1024.0 MiB < 23385.0 MiB. Try running legendary with the --enable-reordering flag to reduce memory usage.

```

I tried using the `--enable-reordering` flag but I still got the same error. I tried with another game (Tyranny) and the installation worked.

Do you have any hint on how to succeed the installation of Pillars? Thanks!

F. Delente

**Comment by CommandMC** [comment]
See https://github.com/derrod/legendary/issues/17#issuecomment-743701890, you're not the only one with this issue
