### ISSUE TITLE
App Name is a bunch of gibberish and I can't seem to download the game through legendary

### ISSUE THREAD

**Issue by cindrmon** [derrod/legendary#160]
Hi!

I just wanted to ask if ever a printed app name in a particular game, let's say GTA V or Cities: Skylines, is pure gibberish, and doesn't have a proper code name, what should I do for that?

This is a snippet of an error if I used that gibberish in place for the app name:
```
C:\Users\cinder>legendary install bcbc03d8812a44c18f41cf7d5f849265 --game-folder E:\EpicGames\CitiesSkylines\
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download...
Traceback (most recent call last):
  File "legendary\cli.py", line 1346, in <module>
  File "legendary\cli.py", line 1314, in main
  File "legendary\cli.py", line 583, in install_game
  File "legendary\core.py", line 710, in prepare_download
  File "legendary\core.py", line 645, in get_cdn_manifest
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://epicgames-download1.akamaized.net/Builds/Org/o-tjvfg6rejs6h86qa7k9aa64rrgbxxb/1608b7d0fddd4d8a85c0454b60a686f0/default/QFPQa9SYbM1yBg1bj0qJDgEfReE0tA.manifest?ak_token=exp%3D1608280337~hmac%3Dc5d3d70fd63f95a84af679e1e481b54ce8c9982340282017c8d253f9016446ff
[3628] Failed to execute script cli
```

**Comment by derrod** [comment]
The app name is just an id, some of them are random and not human readable, that's normal.

The reason it fails is that you're not on the latest verison.

**Comment by cindrmon** [comment]
ok, thanks for the clarification
