### ISSUE TITLE
Legendary doesn't work after a system update

### ISSUE THREAD

**Issue by Foro38** [derrod/legendary#166]
after I updated my archlinux system and now legendary shows an error when trying to launch a game

`Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.5', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1357, in main
    cli.import_game(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 857, in import_game
    if not self.core.login():
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 155, in login
    raise ValueError('No saved credentials')
ValueError: No saved credentials`

is there a way I can fix that?

**Comment by CommandMC** [comment]
That wasn't caused by a system update, your Login token just expired. `legendary auth`

**Comment by Foro38** [comment]
That worked!
thanks
