### ISSUE TITLE
Syncing with EGL fails

### ISSUE THREAD

**Issue by coggy9** [derrod/legendary#183]
I'm trying to setup Legendary on Windows 10 20H2, and upon trying to use the egl-sync feature after logging in, I always get this error. Using release [0.20.6 hotfix](https://github.com/derrod/legendary/releases/tag/0.20.6)

```
[cli] INFO: Reading EGL game manifests...

Checking for importable games...
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1359, in main
  File "legendary\cli.py", line 978, in egs_sync
  File "legendary\core.py", line 1046, in egl_get_importable
  File "legendary\core.py", line 1049, in <listcomp>
  File "legendary\core.py", line 213, in asset_valid
TypeError: 'NoneType' object is not iterable
[12108] Failed to execute script cli
```

**Comment by derrod** [comment]
Run `list-games` first to make sure game metadata is downloaded.

**Comment by derrod** [comment]
I added a check in 58edb22fcebc82fb644a00f7124face3f23e387c so the user receives an error if asset information is not yet available.
