### ISSUE TITLE
Can't run Mud Runner

### ISSUE THREAD

**Issue by major-mayer** [derrod/legendary#186]
Hi there,
I've tried to launch Mud Runner with this CLI application because Lutris doesn't work for me anymore since the last update.
The game should work very well according to the ProtonDB: https://www.protondb.com/app/675010
Logging in was working, but when i try to start the game (on Manjaro Linux) it results in the following error:
```zsh
legendary launch Bulbul                                                                                            
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Bulbul...
~ >>> 0064:err:ole:start_rpcss Failed to start RpcSs service                                                             
00fc:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00fc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00fc:fixme:heap:RtlSetHeapInformation 00000000007C0000 0 000000000021EC00 4 stub
00fc:fixme:heap:RtlSetHeapInformation 0000000000C60000 0 000000000021EC90 4 stub
00fc:fixme:d3d9:D3DPERF_SetOptions (0x1) : stub
0124:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 1): stub
0128:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 2): stub
012c:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 3): stub
0130:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 4): stub
0134:fixme:thread:SetThreadIdealProcessor (FFFFFFFFFFFFFFFE 5): stub
00fc:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr (nil)
```

So i also tried to launch it with `proton-ge-custom` (from the AUR) explicitly specified as the wrapper and the `--no-wine` option, but this results in another error:
```zsh
legendary launch Bulbul --wrapper "/usr/bin/proton"  --no-wine      [130]
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Bulbul...
ProtonLauncher[10079] INFO: empty STEAM_COMPAT_DATA_PATH set to /home/laurenz/.local/share/proton-pfx/0
~ >>> Traceback (most recent call last):                                       
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 926, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 746, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 472, in setup_prefix
    self.update_builtin_libs(builtin_dll_copy)
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 356, in update_builtin_libs
    self.pfx_copy(src_file, dst_file, dll_copy)
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 299, in pfx_copy
    try_copyfile(src, dst)
  File "/usr/share/steam/compatibilitytools.d/proton-ge-custom/proton", line 90, in try_copyfile
    shutil.copyfile(src, dst)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.6/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/games/pfx_proton-ge-custom/drive_c/windows/system32/msvcp110.dll'
``` 

The last idea i had was using proton directly from the steam directory, but this results in yet another error:
```zsh
legendary launch Bulbul --wrapper "/home/laurenz/.local/share/Steam/steamapps/common/Proton\ 5.13/proton"  --no-wine
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Bulbul...
~ >>> Proton: No compat data path?
```

Do you have any ideas?

**Comment by derrod** [comment]
See the wiki on how to configure proton correctly. Otherwise refer to our or other Linux gaming Discord servers for help. This issue tracker is only for legendary issues.
