### ISSUE TITLE
importlib.metadata.PackageNotFoundError: legendary-gl

### ISSUE THREAD

**Issue by ShaddaiSchelin** [derrod/legendary#191]
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/bin/legendary", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: legendary-gl

Please help. How do I fix this?
Thanks!

**Comment by ShaddaiSchelin** [comment]
Nevermind, I reinstalled and now it works fine!
