### ISSUE TITLE
Can't download games

### ISSUE THREAD

**Issue by Jralph4** [derrod/legendary#205]
Hello. I'm trying to install a game (tried with many already) and for some reason this shows up, I already tried to re-login.
```
legendary install Feverfew                                                                                        ─╯
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download...
Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.1', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/cli.py", line 1286, in main
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/cli.py", line 583, in install_game
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/core.py", line 703, in prepare_download
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.20.1-py3.8.egg/legendary/core.py", line 638, in get_cdn_manifest
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://epicgames-download1.akamaized.net/Builds/Org/o-2m9ap45qzvalaepjz6wclpcffeq4aj/Feverfew/default/26wdEJJqHCWch2twyEKwGsxDyWPk4w.manifest?ak_token=exp%3D1610668364~hmac%3D8762650c3e6402f04c52038c3361487f5f0a47c7ce5a53ae611f7f2a59ebd4d8
```

**Comment by CommandMC** [comment]
I think you're not up to date. Epic changed some stuff about their CDN and older versions of legendary don't work anymore

**Comment by Jralph4** [comment]
How do I update Legendary?

**Comment by CommandMC** [comment]
Ah yeah, just looked closer at the log output. You're running 0.20.1, everything below 0.20.3 will not work anymore

**Comment by Jralph4** [comment]
I updated it and now it works. Thanks
