### ISSUE TITLE
ModuleNotFoundError: No module named 'legendary.utils'

### ISSUE THREAD

**Issue by psppwner300** [derrod/legendary#21]
Building the project from source and running `legendary auth` results in this:

`Traceback (most recent call last):
  File "/usr/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.7', 'console_scripts', 'legendary')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/lib/python3.8/site-packages/legendary_gl-0.0.7-py3.8.egg/legendary/cli.py", line 18, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/lib/python3.8/site-packages/legendary_gl-0.0.7-py3.8.egg/legendary/core.py", line 28, in <module>
ModuleNotFoundError: No module named 'legendary.utils'`

This is on an Arch-based distro. Latest version of python is installed, as well as requests and setuptools.

**Comment by derrod** [comment]
Oh yeah I forgot to commit the new setup.py, I'll fix that in a bit.

**Comment by derrod** [comment]
Fixed in https://github.com/derrod/legendary/commit/0b99e568608429a9dd4cfd23ab4f0513c1fef661 please pull the latest code from git and try again.
