### ISSUE TITLE
SSLError: wrong version number

### ISSUE THREAD

**Issue by Pogodaanton** [derrod/legendary#230]
## Platform
| Operating system and version | Legendary version | Package used |
| --- | --- | --- |
| Windows 10 Pro (20H2, build 19042) | 0.20.6 "A Red Letter Day" | Prepackaged EXE |

## Expected Behavior
After you execute `legendary auth` and inserted the SID, Legendary should connect to Epic's services and retrieve necessary tokens.

## Current Behavior
The program freezes and eventually throws the following error message. (SID replaced with a placeholder)

```log
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 496, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.epicgames.com', port=443): Max retries exceeded with url: /id/api/set-sid?sid=AREALSID (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1335, in main
  File "legendary\cli.py", line 125, in auth
  File "legendary\core.py", line 109, in auth_sid
  File "requests\sessions.py", line 555, in get
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.epicgames.com', port=443): Max retries exceeded with url: /id/api/set-sid?sid=AREALSID (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))
[21156] Failed to execute script cli
```

## Steps to Reproduce
> Note that the error occurs with every command that contacts Epic's servers in one way or another.

Until now I have not found a reliable pattern for when this occurs. My current assumption is that it has to do with repeated use of the program, as I have been extensively using `list-games` in the past days and the program started throwing this error after a while every day.

I'll post details should I find sensible patterns for the occurance of the error.

**Comment by derrod** [comment]
Are you using any antivirus software?

**Comment by Pogodaanton** [comment]
Yes, Avast.

**Comment by derrod** [comment]
Okay try turning off "web shield" or whatever it's https interception feature is called, or use an antivirus that doesn't compromise your security through meddling with TLS connections.

**Comment by derrod** [comment]
I might have closed this prematurely, if you're still having an issue feel free to reopen. But I have some experience with antivirus software messing things like this up, so this felt like it's probably the right explanation and solution for what's happening.

**Comment by Pogodaanton** [comment]
Thanks for elaborating on it. I opened up Fiddler and sure enough, I could reproduce my error. At least now I understand what kind of voodoo magic Fiddler does when intercepting HTTPS requests. I have disabled Avast's "HTTPS scanning", hopefully that does the trick.
