### ISSUE TITLE
504/502 Server Error

### ISSUE THREAD

**Issue by SergeyLatyshev** [derrod/legendary#24]
Legandary has just been updated to v0.0.10, and now I can neither download nor launch games:

```
sergey@ryzen:~> legendary install Catnip
[Core] INFO: Trying to re-use existing login session...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.10', 'console_scripts', 'legendary')()
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 564, in main
    cli.install_game(args)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 260, in install_game
    game = self.core.get_game(args.app_name, update_meta=True)
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 149, in get_game
    self.get_game_list(True)
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 153, in get_game_list
    return self.get_game_and_dlc_list(update_assets=update_assets)[0]
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 161, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 137, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.8/site-packages/legendary/api/egs.py", line 97, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
sergey@ryzen:~> legendary list-installed

Installed games:
 * Metro Exodus (App name: Snapdragon, version: 0.1.0.35)

Total: 1
sergey@ryzen:~> legendary launch Snapdragon
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.10', 'console_scripts', 'legendary')()
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 562, in main
    cli.launch_game(args, extra)
  File "/usr/lib/python3.8/site-packages/legendary/cli.py", line 218, in launch_game
    latest = self.core.get_asset(app_name, update=True)
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 143, in get_asset
    self.get_assets(update_assets=True)
  File "/usr/lib/python3.8/site-packages/legendary/core.py", line 137, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.8/site-packages/legendary/api/egs.py", line 97, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live

```

**Comment by derrod** [comment]
Epic is currently having issues, the Epic Games Launcher also doesn't work.

**Comment by SergeyLatyshev** [comment]
> Epic is currently having issues

Haha, classic...
