### ISSUE TITLE
Game verification crashes when game root directory does not exist

### ISSUE THREAD

**Issue by Cydhra** [derrod/legendary#258]
I imported a previously installed game, then uninstalled Epic Launcher itself (which deleted the game path).
But when I tried to reinstall the game via legendary, it failed, because legendary apparently cached which version was installed and refused to update that, as it was the latest version (even thought the entire path had been deleted).
So I tried to verify the game, so legendary would recognize the missing game files. But since the path did not exist anymore (i.e. the root directory of the game), it crashed.

## Platform

Operating system and version: Windows 10
Legendary version (`legendary -V`): 0.20.6 "A Red Letter Day"

## Expected Behavior
legendary should notice, at the latest when verifying the game, that the path is gone and therefore the game is not installed anymore. (Though it should ask the user if it is really gone, maybe there is just a missing network drive, or an unmounted/encrypted drive)

## Current Behavior

```
> legendary.exe verify-game CrabTest
[cli] INFO: Loading installed manifest for "CrabTest"
[cli] INFO: Verifying "Satisfactory Experimental" version "147217"
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1355, in main
  File "legendary\cli.py", line 810, in verify_game
  File "legendary\utils\lfs.py", line 91, in validate_files
OSError: Path does not exist
[5048] Failed to execute script cli
```

## Steps to Reproduce

1. Install a game
2. Delete the game **including its root directory** (so the path to the game is incomplete)
3. Try to verify the game

### Hotfix for users
Since this is an issue with the handling of the path, the _hotfix_ for affected users until the bug has been resolved is pretty easy:
Just manually create every folder of the game path (legendary will tell you the full path when you try to install the game). Then run `verify-game` again.

**Comment by nutterthanos** [comment]
well actually would it be better to remove the game from legendary database?

**Comment by Cydhra** [comment]
Better than what?

**Comment by nutterthanos** [comment]
than the current hotfix

**Comment by Cydhra** [comment]
Well obviously. The hotfix is only for **users** until the bug has been fixed. This is why I submitted the issue here.

**Comment by nutterthanos** [comment]
yes
