### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lordofwizard** [derrod/legendary#260]
Sorry i don't know much i am a noob
```
legendary version "0.20.1", codename "Endgame"
```

```
lordofwizard@pop-os:~$ legendary install 0dac2fd1f95240bda133d1f2fb27c705
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download...
Traceback (most recent call last):
  File "/home/lordofwizard/.local/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/home/lordofwizard/.local/lib/python3.8/site-packages/legendary/cli.py", line 1286, in main
    cli.install_game(args)
  File "/home/lordofwizard/.local/lib/python3.8/site-packages/legendary/cli.py", line 583, in install_game
    dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
  File "/home/lordofwizard/.local/lib/python3.8/site-packages/legendary/core.py", line 703, in prepare_download
    new_manifest_data, _base_urls = self.get_cdn_manifest(game, platform_override)
  File "/home/lordofwizard/.local/lib/python3.8/site-packages/legendary/core.py", line 638, in get_cdn_manifest
    r.raise_for_status()
  File "/home/lordofwizard/.local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://epicgames-download1.akamaized.net/Builds/Org/o-c4wvnkapw72ewsv6plkytlbc5f46nb/dfcabf36708049778a5b3df3a770e7cd/default/k_PXktx82L_Lf1noTEOer5PwRT_iZw.manifest?ak_token=exp%3D1617521845~hmac%3D7eacf31a175744558b62785e73891559d4da707175ea6b3e385566f7ae1a2101
```

**Comment by derrod** [comment]
Update your legendary version.

**Comment by lordofwizard** [comment]
> Update your legendary version.

Yeah right did it
