### ISSUE TITLE
Legendary says that I'm auth'ed successfully, but list-games does not work

### ISSUE THREAD

**Issue by DictumMortuum** [derrod/legendary#267]
## Platform

Operating system and version: archlinux
Legendary version (`legendary -V`): legendary version "0.20.6", codename "A Red Letter Day"

## Expected Behavior
It should retrieve the list of games

## Current Behavior
It does not

```
❯ legendary auth
[cli] INFO: Testing existing login data if present...
Please login via the epic web login!
If web page did not open automatically, please manually open the following URL: https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect
Please enter the "sid" value from the JSON response: << redacted >>
[cli] INFO: Successfully logged in as "<< redacted >>"

~ 22s
❯ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1337, in main
    cli.list_games(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 146, in list_games
    games, dlc_list = self.core.get_game_and_dlc_list(
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.9/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

## Steps to Reproduce
1. Login with token
2. List games

**Comment by derrod** [comment]
Cannot reproduce, is this still happening? Might have been just a temporary issue.

**Comment by DictumMortuum** [comment]
Yes it does. Could it be something related to my account / location?

```
~
❯ legendary auth --delete

~
❯ legendary auth
[cli] INFO: Testing existing login data if present...
Please login via the epic web login!
If web page did not open automatically, please manually open the following URL: https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect
Please enter the "sid" value from the JSON response: "<< sid >>"
[cli] INFO: Successfully logged in as "<< username >>"

~ 15s
❯ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1337, in main
    cli.list_games(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 146, in list_games
    games, dlc_list = self.core.get_game_and_dlc_list(
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.9/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

**Comment by syto203** [comment]
try using a VPN.

**Comment by DictumMortuum** [comment]
Trying with a VPN results in the same error:

```
❯ ps -ef | grep "openvpn"
root        4257    4066  0 09:03 pts/1    00:00:00 sudo openvpn client3.ovpn
root        4258    4257  1 09:03 pts/1    00:01:14 openvpn client3.ovpn

~
❯ legendary auth
[cli] INFO: Testing existing login data if present...
Please login via the epic web login!
If web page did not open automatically, please manually open the following URL: https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect
Please enter the "sid" value from the JSON response: "<< sid >>"
[cli] INFO: Successfully logged in as "<< user >>"

~ 18s
❯ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1337, in main
    cli.list_games(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 146, in list_games
    games, dlc_list = self.core.get_game_and_dlc_list(
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.9/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

**Comment by syto203** [comment]
try deleting the config directory and start from scratch with a new session id and remember to close any other active epic launchers on any platform.

**Comment by DictumMortuum** [comment]
Doesn't work. I have never installed the epic launcher, as I don't own any windows machines.

```
❯ rm -rf .config/legendary

~
❯ legendary auth
[cli] INFO: Testing existing login data if present...
Please login via the epic web login!
If web page did not open automatically, please manually open the following URL: https://www.epicgames.com/id/login?redirectUrl=https://www.epicgames.com/id/api/redirect
Please enter the "sid" value from the JSON response: "<< sid >>"
[cli] INFO: Successfully logged in as "<< username >>"

~ 16s
❯ legendary list-games
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1337, in main
    cli.list_games(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 146, in list_games
    games, dlc_list = self.core.get_game_and_dlc_list(
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.9/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

**Comment by syto203** [comment]
after the initial successful login navigate to the config directory and open "user.json" and check if it has the access token and your account id.

**Comment by DictumMortuum** [comment]
- the displayName in that json file is correct.
- the client_id, account_id, in_app_id, device_id is something similar sid. They're not the same, but they're random strings with the same length.
- the access_token is a very large string, takes up multiple lines and starts with "eg1~". The same is true for the refresh_token, but it's a bit shorter in length.
- token_type: bearer

**Comment by syto203** [comment]
next run 
`legendary status`

**Comment by DictumMortuum** [comment]
It's the same error with list-games:

```
❯ legendary status
[Core] INFO: Trying to re-use existing login session...
[EPCAPI] WARNING: Login to EGS API failed with errorCode: errors.com.epicgames.common.authentication.authentication_failed
[Core] WARNING: Resuming failed due to invalid credentials: InvalidCredentialsError('errors.com.epicgames.common.authentication.authentication_failed')
[Core] INFO: Falling back to using refresh token...
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "/usr/bin/legendary", line 33, in <module>
    sys.exit(load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')())
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1361, in main
    cli.status(args)
  File "/usr/lib/python3.9/site-packages/legendary/cli.py", line 1034, in status
    games_available = len(self.core.get_game_list(update_assets=not args.offline))
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 221, in get_game_list
    return self.get_game_and_dlc_list(update_assets=update_assets)[0]
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/usr/lib/python3.9/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/usr/lib/python3.9/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

**Comment by syto203** [comment]
try to create a new account and check.

**Comment by DictumMortuum** [comment]
Alright I'll try with a new account - btw do the quotes matter when copying the sid?

**Comment by syto203** [comment]
dont include the quotes

**Comment by nutterthanos** [comment]
did you try with an new account?

**Comment by DictumMortuum** [comment]
@nutterthanos I didn't - I'll try to do it soon.

**Comment by nutterthanos** [comment]
> @nutterthanos I didn't - I'll try to do it soon.
👍

**Comment by nutterthanos** [comment]
@DictumMortuum its been 16 days have you like forgot about this or your busy with irl things?

**Comment by hvcrios** [comment]
This happened to me once, and the problem was the DNS, using a different DNS server solved it, though if that was the case, when you tried the VPN it should have worked.

**Comment by derrod** [comment]
Closed due lack of reproducability and response.

**Comment by nutterthanos** [comment]
> This happened to me once, and the problem was the DNS, using a different DNS server solved it, though if that was the case, when you tried the VPN it should have worked.

Weird how it can be DNS server tho being how you said trying vpn didn't fix it

**Comment by DictumMortuum** [comment]
I try every so often, whenever I see an upgraded package, but no luck .

I even opened a ticket on the official dev support for the error, but they
weren't helpful at all :(

**Comment by nutterthanos** [comment]
Actually does logon on epicgames.com work fine tho or in egl?

**Comment by Formedras** [comment]
Is it possible that this is a 2FA related issue?

I have the problem too now that even after logging in and giving the sid to Legendary, I still can't use list-games or status. But when I opened Epic's launcher, I had to log in there too, and I noticed that while the base login process is in-browser, the launcher itself is what took my 2FA code.
