### ISSUE TITLE
Hi, i try install game, but have error

### ISSUE THREAD

**Issue by steambsd** [derrod/legendary#283]
legendary install a579a08e71b341e6af106dbd170e2ab2
[Core] INFO: Logging in...
[cli] INFO: Preparing download...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x8030c2430>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='epicgames-download1.akamaized.net', port=443): Max retries exceeded with url: /Builds/Org/o-f4rsv826ngcpw4wvunwntql3n23m46/d31b4d61b3f749c388e4c94bd08bc5b6/default/ZBvyZFsDd7oKBXtJwEe_BNgJxMDw3A.manifest?ak_token=exp=1623155557~hmac=e067e5cddd00f18c4ecc4478dfc1ddb310f70034eae9054feca9de861024b685 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x8030c2430>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.20.6', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/site-packages/legendary_gl-0.20.6-py3.8.egg/legendary/cli.py", line 1351, in main
  File "/usr/local/lib/python3.8/site-packages/legendary_gl-0.20.6-py3.8.egg/legendary/cli.py", line 596, in install_game
  File "/usr/local/lib/python3.8/site-packages/legendary_gl-0.20.6-py3.8.egg/legendary/core.py", line 736, in prepare_download
  File "/usr/local/lib/python3.8/site-packages/legendary_gl-0.20.6-py3.8.egg/legendary/core.py", line 670, in get_cdn_manifest
  File "/usr/local/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='epicgames-download1.akamaized.net', port=443): Max retries exceeded with url: /Builds/Org/o-f4rsv826ngcpw4wvunwntql3n23m46/d31b4d61b3f749c388e4c94bd08bc5b6/default/ZBvyZFsDd7oKBXtJwEe_BNgJxMDw3A.manifest?ak_token=exp=1623155557~hmac=e067e5cddd00f18c4ecc4478dfc1ddb310f70034eae9054feca9de861024b685 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x8030c2430>: Failed to establish a new connection: [Errno 60] Operation timed out'))
[admin@ ~]$

**Comment by steambsd** [comment]
Just many test games
