### ISSUE TITLE
Can't run any command or launch games, returns traceback. 

### ISSUE THREAD

**Issue by rafamadriz** [derrod/legendary#284]
## Platform

Operating system and version: Linux mintdesktop 5.4.0-74-generic
Legendary version (`legendary -V`):  legendary version "0.20.6", codename "A Red Letter Day"

## Expected Behavior

Run commands normally, e.g. list games, list installed games, launch games, etc.

## Current Behavior

It gives a traceback for any command. 

## Steps to Reproduce

1. run legendary list-games

## Additional information

This is the output. It was all working fine yesterday. 
```
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
Traceback (most recent call last):
  File "/home/rafa/.local/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/home/rafa/.local/lib/python3.8/site-packages/legendary/cli.py", line 1337, in main
    cli.list_games(args)
  File "/home/rafa/.local/lib/python3.8/site-packages/legendary/cli.py", line 146, in list_games
    games, dlc_list = self.core.get_game_and_dlc_list(
  File "/home/rafa/.local/lib/python3.8/site-packages/legendary/core.py", line 229, in get_game_and_dlc_list
    for ga in self.get_assets(update_assets=update_assets,
  File "/home/rafa/.local/lib/python3.8/site-packages/legendary/core.py", line 199, in get_assets
    self.lgd.assets = [GameAsset.from_egs_json(a) for a in self.egs.get_game_assets()]
  File "/home/rafa/.local/lib/python3.8/site-packages/legendary/api/egs.py", line 101, in get_game_assets
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live
```

**Comment by Flonky** [comment]
Epic is currently having issues, ig this is why it generates an bad web request
