### ISSUE TITLE
pip install legendary-gl fails

### ISSUE THREAD

**Issue by adrianlshaw** [derrod/legendary#29]
It appears in pip search but it can't be installed.

```sh
user@machine:~> pip install legendary-gl -vvv
Collecting legendary-gl
  1 location(s) to search for versions of legendary-gl:
  * https://pypi.python.org/simple/legendary-gl/
  Getting page https://pypi.python.org/simple/legendary-gl/
  Looking up "https://pypi.python.org/simple/legendary-gl/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/legendary-gl/" in the cache
  Current age based on date: 83
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 83
  Analyzing links from page https://pypi.org/simple/legendary-gl/
    The package https://files.pythonhosted.org/packages/0a/2c/df4fbafe51810adfc77de835f203bee6d820003d234ff21b8140052479ac/legendary-gl-0.0.6.tar.gz#sha256=d7ce4cb5cbfc8538574892e57dd89fb54d5210938d8260f1726683f3310c7894 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/49/d6/97bbf7722eb5efb3a16762d3f1ee962ddcb9e25a4ed5204b6d6309ac97ce/legendary_gl-0.0.6-py3-none-any.whl#sha256=49654036744f50b71c1074f7e62edc661baa164167d64bf570b177e179792035 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/fe/93/2c2df59311c6181035bf397a81265bce3d316167d380106b33ac7100ef13/legendary-gl-0.0.7-3.tar.gz#sha256=2a1c10781586de00eb155650f8ad3e9aca8366d743761000290832e2d349476b (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/96/f8/a00b8b905d44d13578408f7f4385332eb865be6bee86e5ae5281799bf83f/legendary_gl-0.0.7-3-py3-none-any.whl#sha256=10d4dfe9f57f01b4e3d00e10458a9981ef8701ef41c3395f012c1eca79b020d2 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/cd/99/6ab7417206a2bf48a8800f1e1e17b8e50c2619c7f25c786a7b1cc10ff0a8/legendary-gl-0.0.8.tar.gz#sha256=3c9367f844144b47b7f4c292640d00ac94406f7fd2cb32dc2fdcb8ba4f560e15 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/e9/a0/31bf1b1085c14a046e508e64473bb2b269bb095ddf9b5a0b1b36a540978b/legendary_gl-0.0.8-py3-none-any.whl#sha256=fdac34b9f8606e55bffb54b23c7c156e580e8977a90ea158c5cbb3ed58430c7c (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/92/4f/c067da0ae1852b8db0e6fa89d0d61172cbe11e8629c45c3c6e9e19d66a36/legendary-gl-0.0.9.tar.gz#sha256=aaa64bc0f862b04a0b44d6f4496fdd3ca8508bcb119ff35483938c143266c29a (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/35/ff/65cea0419679f9ef33a5a79374f81e8a8a32711bd62ba8ae5ec824cc8876/legendary_gl-0.0.9-py3-none-any.whl#sha256=f458e3aac4e611f9f76061fe8ec436c7e440b2a2c1c84779b847adf24c5aa4e3 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/c6/d5/15b541e63a41d2ddee290d5a36d6cebac07d03331b8c2e552fea8779d9a5/legendary-gl-0.0.10.tar.gz#sha256=5c06428e54c6ff497858031fe1c4138c9ce5c11b45fc65f7896eb2052d624d0c (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/99/24/71b1feb085dddf81fd94ec538b08c60a366bdc84261a92c2e119f0779410/legendary_gl-0.0.10-py3-none-any.whl#sha256=623a75af26fc9c0a029a325c46b25c3ea4364f00bb1f827cf18a002070292fce (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
    The package https://files.pythonhosted.org/packages/61/59/d5e4e63262238395523589317c098488f7192654d073655e2a979bff9d5b/legendary-gl-0.0.11.tar.gz#sha256=848e1ee6d724b1e089ee2aa97ab9e8c3a8b2eaa2b33407d617d154a86d2bedd8 (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8) is incompatible with the pythonversion in use. Acceptable python versions are:>=3.8
    Skipping link https://files.pythonhosted.org/packages/d1/3e/c9f1a3e3ccc1d5f7829a66ec54c94006e8c08309eb8e38916bb3238eda9d/legendary_gl-0.0.11-py3-none-any.whl#sha256=1c2fa525b9524743e4ff4d739435d3f5d21b934737d619f5ca153d19f184bf6d (from https://pypi.org/simple/legendary-gl/) (requires-python:>=3.8); it is not compatible with this Python
  Could not find a version that satisfies the requirement legendary-gl (from versions: )
Cleaning up...
No matching distribution found for legendary-gl
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for legendary-gl

```

**Comment by VodBox** [comment]
The pip command you're running is for a Python 2.7 install. Legendary requires — and only has a package on PyPI for — Python 3.8 and higher. You can try running `pip3` or `python3 -m pip` in place of `pip` to force using your install of Python 3. Either way, this is not an issue with the Legendary package itself.

**Comment by derrod** [comment]
Legendary requires python3.8+.
