### ISSUE TITLE
Namespace' object has no attribute 'wine_bin' upon launching GTA V

### ISSUE THREAD

**Issue by t0stiman** [derrod/legendary#31]
```
legendary launch 9d2d0eb64d5c44529cece33fe2a46482
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
Traceback (most recent call last):
  File "legendary\cli.py", line 795, in <module>
  File "legendary\cli.py", line 771, in main
  File "legendary\cli.py", line 373, in launch_game
AttributeError: 'Namespace' object has no attribute 'wine_bin'
[9280] Failed to execute script cli
```

Windows 10 x64

**Comment by derrod** [comment]
Fixed in https://github.com/derrod/legendary/commit/7d919c1f2ae6b60e1b85931a5c9c3d56596abc00 download the latest release or update from PyPI with `py -3.8 -m pip install -U legendary-gl`
