### ISSUE TITLE
IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by unchilled** [derrod/legendary#324]
## Platform

Operating system and version: Windows 11 Enterprise 21H2 build 22000.168 and WSL 2
Legendary version (`legendary -V`): 0.20.6, "A Red Letter Day"

## Expected Behavior

Install an older version of Fortnite using a manifest file.

## Current Behavior

```
PS D:\Games\Fortnite\legendary> ./legendary --debug install Fortnite --manifest ./9.41.txt
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Trying to re-use existing login session...
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
You are about to install Fortnite, this game supports selective downloads.
The following optional packs are available:
 * stw - Fortnite Save the World
 * hd_textures - High Resolution Textures
 * lang_de - (Language Pack) Deutsch
 * lang_fr - (Language Pack) français
 * lang_pl - (Language Pack) polski
 * lang_ru - (Language Pack) русский
 * lang_cn - (Language Pack) 中文（中国）
Please enter a comma-separated list of optional packs to install (leave blank for defaults)
Additional packs [e.g. stw,hd_textures]:
[cli] INFO: Preparing download...
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Overriding manifest with "./9.41.txt"
[Core] INFO: Parsing game manifest...
[Core] DEBUG: Base urls: []
[LGDLFS] DEBUG: Failed to load installed game data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Install path: C:\Users\unchilled/legendary\Fortnite
Traceback (most recent call last):
  File "legendary\cli.py", line 1375, in <module>
  File "legendary\cli.py", line 1343, in main
  File "legendary\cli.py", line 595, in install_game
  File "legendary\core.py", line 809, in prepare_download
  File "random.py", line 290, in choice
IndexError: Cannot choose from an empty sequence
[6392] Failed to execute script cli
```

## Steps to Reproduce

1. Download Fortnite manifest file. I downloaded mine from [https://github.com/VastBlast/FortniteManifestArchive](https://github.com/VastBlast/FortniteManifestArchive) and tested with multiple versions including 9.41 and 10.40
2. Run `legendary install Fortnite --manifest 9.41.txt`
3. No optional download packs.

## Additional information

I've attempted this with the .exe as well as the .deb on WSL. I've also attached a couple of the manifests I tried using.
[9.41.txt](https://github.com/derrod/legendary/files/7072818/9.41.txt)
[10.40.txt](https://github.com/derrod/legendary/files/7072819/10.40.txt)

**Comment by derrod** [comment]
You haven't specified any CDN to download from (see `--base-url`).
