### ISSUE TITLE
ModuleNotFoundError: No module named 'legendary.downloader.mp'

### ISSUE THREAD

**Issue by woctezuma** [derrod/legendary#327]
## Platform
Operating system and version: Windows 10 20H2 19042.1165
Legendary version: 0.20.7

## Expected Behavior
To be able to run `legendary`.

## Current Behavior
```bash
$ legendary -V

Traceback (most recent call last):
  File "c:\users\wok\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wok\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wok\AppData\Local\Programs\Python\Python39\Scripts\legendary.exe\__main__.py", line 4, in <module>
  File "c:\users\wok\appdata\local\programs\python\python39\lib\site-packages\legendary\cli.py", line 21, in <module>
    from legendary.core import LegendaryCore
  File "c:\users\wok\appdata\local\programs\python\python39\lib\site-packages\legendary\core.py", line 20, in <module>
    from legendary.downloader.mp.manager import DLManager
ModuleNotFoundError: No module named 'legendary.downloader.mp'
```

## Steps to Reproduce
```bash
pip install --upgrade legendary-gl
legendary -V
```

**Comment by derrod** [comment]
This is now fixed and the broken release has been yanked from PyPI, it might take a bit for the new version to become available. Simply update again in a few minutes.
