### ISSUE TITLE
Can't install old (and latest) Fortnite through manifest

### ISSUE THREAD

**Issue by PRiiXX** [derrod/legendary#334]
Hey so I'm currently trying to install an old version of Fortnite. I'm looking for version 2.3.0 which has the manifest "ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f"
I always get this error:

```
Legendary version: 0.20.9 - "Water Hazard"
Update available: no

C:\Users\Sebastian\Downloads\leg>legendary install Fortnite --manifest http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f.manifest
[Core] INFO: Trying to re-use existing login session...
You are about to install Fortnite, this game supports selective downloads.
The following optional packs are available:
 * stw - Fortnite Save the World
 * hd_textures - High Resolution Textures
 * lang_de - (Language Pack) Deutsch
 * lang_fr - (Language Pack) français
 * lang_pl - (Language Pack) polski
 * lang_ru - (Language Pack) русский
 * lang_cn - (Language Pack) 中文（中国）
Please enter a comma-separated list of optional packs to install (leave blank for defaults)
Additional packs [e.g. stw,hd_textures]:
[cli] INFO: Preparing download...
[Core] INFO: Overriding manifest with "http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f.manifest"
Traceback (most recent call last):
  File "legendary\cli.py", line 1451, in <module>
  File "legendary\cli.py", line 1410, in main
  File "legendary\cli.py", line 626, in install_game
  File "legendary\core.py", line 811, in prepare_download
  File "legendary\core.py", line 757, in get_uri_manifest
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/ZrI2-mGi5f095bc735dd412085dd6e71f5f1072f.manifest
[30436] Failed to execute script cli
```

I then tried to install the latest Fortnite through the manifest which is "hbkx_qhpofyAGF3VQUaU-0ke3WwKBg" for 17.50 but it gives me the same error as above. The only thing that works though is just a simple
`legendary install Fortnite`
but obviously I don't need it as I want to install an older version for datamining purposes.

Is there anything I did wrong or how I can fix it?

**Comment by derrod** [comment]
The CDN requries authentication.

**Comment by PRiiXX** [comment]
but I already did auth, and it says my credentials are still valid. so?

**Comment by derrod** [comment]
You're authenticated with the epic api, not the CDN. You cannot authenticate with the CDN for anything but the latest version, which is what legendary does when you run a normal install/update.
