### ISSUE TITLE
Unreal Engine 4.27 can't be downloaded by Legendary?

### ISSUE THREAD

**Issue by LRSFC-DanJ** [derrod/legendary#364]
## Platform

Operating system and version: Windows 10 Enterprise 20H2
Legendary version (`legendary -V`): legendary version "0.20.18", codename "Entanglement (hotfix)"

## Expected Behavior

Unreal Engine 4.27 files are downloaded

## Current Behavior

Unhandled exception
Output of legendary:
```
[cli] INFO: Setting --no-install flag since "download" command was used
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Unreal Engine" (UE_4.27)...
Traceback (most recent call last):
  File "legendary\cli.py", line 2095, in <module>
  File "legendary\cli.py", line 2036, in main
  File "legendary\cli.py", line 801, in install_game
  File "legendary\core.py", line 1072, in prepare_download
  File "legendary\core.py", line 1004, in get_cdn_manifest
  File "legendary\core.py", line 980, in get_cdn_urls
  File "legendary\api\egs.py", line 125, in get_game_manifest
  File "requests\models.py", line 953, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/v2/platform/windows/namespace/ue/catalogItem/3ddb1bad6e004b99a7192c1a29f2318a/app/UE_4.27/label/Live
[62752] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce

1. Authenticate Legendary to your Epic Games account with Unreal Engine on the account.
2. `legendary.exe download UE_4.27 --include-ue --base-path D:\UE --download-only --platform windows --install-tag starter_content --install-tag templates --install-tag engine_source --install-tag platform_Android --install-tag platform_IOS --install-tag platform_Linux --install-tag ""` but replace D:\UE with a folder to download the Unreal Engine files into.

## Additional information

This worked fine for Unreal Engine 4.26, so not sure why it doesn't work for 4.27?

**Comment by derrod** [comment]
`windows` isn't a valid platform, it has to be `WIndows` instead.
