### ISSUE TITLE
Problem with the "cleanup" command

### ISSUE THREAD

**Issue by hvcrios** [derrod/legendary#378]
## Platform
Linux Mint 20.2, using the standard package downloaded from the releases section, version 0.20.21

## Expected Behavior
The command should just run normally

## Current Behavior
I get this error message:

```
Traceback (most recent call last):
  File "legendary/cli.py", line 2305, in <module>
  File "legendary/cli.py", line 2262, in main
  File "legendary/cli.py", line 1741, in cleanup
TypeError: unsupported operand type(s) for |=: 'dict' and 'set'
[12430] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce
1. just type in "legendary cleanup"

**Comment by CommandMC** [comment]
Running `legendary list-games` (optionally with the `--force-refresh` option) should solve this.
Metadata changed a bit
