### ISSUE TITLE
Error when importing epic installed games, not recognised.

### ISSUE THREAD

**Issue by Lastxuan203954** [derrod/legendary#383]
## Platform

Operating system and version:windows10 19042.1348
Legendary version (`legendary -V`):0.20.22

## Expected Behavior
It should recognise RDR2 that has been installed via epic and can be booted via legendary.

## Current Behavior
Repeated unknown error, does not seem to recognise the game root.

## Steps to Reproduce

1.D:\>legendary import-game Heather "D:\Epic Games\RedDeadRedemption2"
2.Traceback (most recent call last):
3. File "legendary\cli.py", line 2316, in <module>
  File "legendary\cli.py", line 2261, in main
  File "legendary\cli.py", line 1100, in import_game
  File "legendary\core.py", line 1030, in is_installed
  File "legendary\core.py", line 547, in get_installed_game
  File "legendary\core.py", line 1637, in egl_sync
  File "legendary\lfs\egl.py", line 52, in read_manifests
  File "json\__init__.py", line 293, in load
4.UnicodeDecodeError: 'gbk' codec can't decode byte 0xb9 in position 186: illegal multibyte sequence
[7580] Failed to execute script 'cli' due to unhandled exception!

## Additional information
The previous commands all work, such as getting a list of games, but importing games doesn't work, nor does starting them.
![((T9G3(84@()P}7WF9LF7WH](https://user-images.githubusercontent.com/96333553/147196514-7b8145fe-b799-41f1-9370-19f4445ced09.png)

**Comment by derrod** [comment]
Try the Windows build from CI to see if that fixes it: https://github.com/derrod/legendary/suites/4743700406/artifacts/131134589
