### ISSUE TITLE
List Windows-only games on macOS if WINE is installed

### ISSUE THREAD

**Issue by benthetechguy** [derrod/legendary#385]
**Is your feature request related to a problem? Please describe.**
On macOS, when I run `legendary list-games`, I only see native Mac games even though I have WINE installed.

**Describe the solution you'd like**
Legendary should check if WINE is installed and add Windows-only games to the list if it is detected.

**Describe alternatives you've considered**
I have attempted to install a game in my library that isn't in the list, and it gives a 404 error, presumably because it's attempting to find and download a Mac version of the game that doesn't exist.

**Additional context**
Here's the full error I received with that attempt:
```
ben@Mac-Mini ~ % legendary install Discus
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "For The King" (Discus)...
Traceback (most recent call last):
  File "/opt/homebrew/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/cli.py", line 2245, in main
    cli.install_game(args)
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/cli.py", line 820, in install_game
    dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/core.py", line 1145, in prepare_download
    new_manifest_data, base_urls = self.get_cdn_manifest(game, platform)
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/core.py", line 1077, in get_cdn_manifest
    manifest_urls, base_urls = self.get_cdn_urls(game, platform)
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/core.py", line 1054, in get_cdn_urls
    m_api_r = self.egs.get_game_manifest(game.namespace, game.catalog_item_id,
  File "/opt/homebrew/lib/python3.9/site-packages/legendary/api/egs.py", line 141, in get_game_manifest
    r.raise_for_status()
  File "/opt/homebrew/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/public/assets/v2/platform/Mac/namespace/4492ce99b4124b74a0bb83f78b3d70b8/catalogItem/430f4445291f4566989cc26039f4694c/app/Discus/label/Live
```

**Comment by CommandMC** [comment]
`legendary list-games` can take an optional `--platform` argument. You can list Windows-only games with `legendary list-games --platform Windows` for example.
`install` works the same way.

**Comment by benthetechguy** [comment]
Thank you, I somehow missed this while reading the help message.
