### ISSUE TITLE
Unable to link accounts and error reported

### ISSUE THREAD

**Issue by Lastxuan203954** [derrod/legendary#386]
## Platform

Operating system and version:windows10 19042.1348
Legendary version (`legendary -V`): v0.20.22

## Expected Behavior
Ability to link accounts and successfully launch the game

## Current Behavior
Unable to link accounts and error reported

## Steps to Reproduce

1.D:\>legendary auth
2.[cli] INFO: Testing existing login data if present...
[Core] WARNING: Checking for Legendary updates failed: SSLError(MaxRetryError("HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"))
3.[Core] INFO: Logging in...
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)
4.Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
![image](https://user-images.githubusercontent.com/96333553/147569896-c8f234e9-c34f-4b13-ae5b-bd39002113f2.png)
![image](https://user-images.githubusercontent.com/96333553/147569918-f8d57ddb-c2b3-403c-bf48-6e92d714b888.png)

**Comment by derrod** [comment]
The connetion to both the Epic and Legendary API is failing due to some SSL error, this may be due to your system having a proxy configured that isn't working correctly, or some other network issue occuring. I cannot fix that from my end.
