### ISSUE TITLE
Legendary auth fails on a fresh installation using manual installation or pip installation on Ubuntu 20

### ISSUE THREAD

**Issue by Dadadah** [derrod/legendary#411]
## Platform

Operating system and version: Ubuntu 20
Legendary version (`legendary -V`): Latest (v0.20.25)

## Expected Behavior

Legendary should open a web view UI when asked to authenticate.

## Current Behavior

Legendary fails to open the web view UI and fails to authenticate.

```
USER:~$ legendary auth
[cli] INFO: Testing existing login data if present...
[WebViewHelper] INFO: Opening Epic Games login window...
[pywebview] loaded event is deprecated and will be removed in 4.0. Use events.loaded instead
[pywebview] WARNING: loaded event is deprecated and will be removed in 4.0. Use events.loaded instead
Traceback (most recent call last):
  File "/home/jschlecht/.local/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/home/jschlecht/.local/lib/python3.8/site-packages/legendary/cli.py", line 2917, in main
    cli.auth(args)
  File "/home/jschlecht/.local/lib/python3.8/site-packages/legendary/cli.py", line 168, in auth
    if do_webview_login(callback_sid=self.core.auth_sid, callback_code=self.core.auth_code):
  File "/home/jschlecht/.local/lib/python3.8/site-packages/legendary/utils/webview_login.py", line 130, in do_webview_login
    window.loaded += api.on_loaded
AttributeError: can't set attribute
```

## Steps to Reproduce

1. Install legendary using PIP or manual installation on an Ubuntu machine with python 3 installed via apt
2. Launch `legendary auth`

## Additional information

I modified the utils/webview_login.py file to have an INFO loglevel. This seems to be a deprecation issue with pywebview. I was able to get the webview to launch and auth to work by changing line 130 to `window.events.loaded += api.on_loaded`

**Comment by derrod** [comment]
Try downgrading pywebview via `pip install -U --force pywebview<4.0`. I guess I need to adjust the requirements/setup file.

**Comment by aznd** [comment]
@derrod 
Btw, that command won't work. It would redirect the file 4.0.
Also, the latest version of pywebview is 3.6.3

**Comment by derrod** [comment]
Yeah I forgot the quotes there.

Weird that they already broke it in 3.6 when it's only deprecated :/ I'll have to fix that eventually.
