### ISSUE TITLE
Problem with the Verify command

### ISSUE THREAD

**Issue by MinerPL** [derrod/legendary#412]
## Platform

Operating system and version: Windows 11 Build 22557.1 (Dev Insider)
Legendary version (`legendary -V`): legendary version "0.20.25", codename "Our Benefactors"

## Expected Behavior
Legendary should verify the current files 

## Current Behavior
Legendary throws error posted below

```
C:\Users\minerpl>legendary verify Fortnite
[cli] INFO: Loading installed manifest for "Fortnite"
[cli] INFO: Verifying "Fortnite" version "++Fortnite+Release-19.20-CL-18775446-Windows"
[cli] ERROR: File is missing: ".unsync/manifest.bin"
Traceback (most recent call last):
  File "C:\Users\minerpl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\minerpl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\minerpl\AppData\Local\Programs\Python\Python310\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "C:\Users\minerpl\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 2935, in main
    cli.verify_game(args)
  File "C:\Users\minerpl\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 1177, in verify_game
    speed = (processed - last_processed) / 1024 / 1024 / delta
ZeroDivisionError: float division by zero
```

## Steps to Reproduce

1. Import Fortnite from Epic Games
2. Try verify Files
3. Get error

**Comment by woctezuma** [comment]
Not sure why the error happens at line 1177. It should be at line 1181:
https://github.com/derrod/legendary/blob/d7360eef3e2ed5816da5549d71d5bce57e129df3/legendary/cli.py#L1179-L1182

**Comment by MinerPL** [comment]
> Thus, maybe update your version of `legendary`.

As far as I can see, I have the latest version.

**Comment by woctezuma** [comment]
Right, the line difference must be due to this commit:
- 7ac9ec7b5f9a0aa35eb7042e8184e1d46c085707
