### ISSUE TITLE
Trying to install the EOS overlay fails (and crashes Legendary)

### ISSUE THREAD

**Issue by furokku** [derrod/legendary#440]
## Platform

Operating system and version: Arch Linux
Legendary version (`legendary -V`): legendary version "0.20.26", codename "Dark Energy"

## Expected Behavior

Legendary should install the EOS overlay without issues.

## Current Behavior

After the download, an unhandled exception occurs and the overlay is not installed (this happens with both the `eos-overlay install` and `eos-overlay enable` arguments, perhaps others too)

Log:
```
~ » /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay install --prefix /mnt/games/heroic/Prefixes/FallGuys --path /mnt/games/heroic/.overlay
[cli] INFO: Using prefix "/mnt/games/heroic/Prefixes/FallGuys"
[cli] INFO: Preparing to start overlay install...
[cli] INFO: Install directory: /mnt/games/heroic/.overlay
[cli] INFO: Install size: 330.70 MiB
[cli] INFO: Download size: 141.46 MiB
Do you want to install the overlay? [Y/n]: y
[DLManager] INFO: Download Manager running with process-id: 131064
[DLManager] INFO: Starting download workers...
[DLManager] INFO: Starting file writing worker...
[DLManager] INFO: = Progress: 0.00% (0/3944), Running for 00:00:00, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 0.00 MiB, Written: 0.00 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 0.00 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 0.35% (14/3944), Running for 00:00:01, ETA: 00:04:42
[DLManager] INFO:  - Downloaded: 6.49 MiB, Written: 14.00 MiB
[DLManager] INFO:  - Cache usage: 19.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 6.49 MiB/s (raw) / 16.98 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 13.98 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 43.86% (1730/3944), Running for 00:00:02, ETA: 00:00:02
[DLManager] INFO:  - Downloaded: 17.75 MiB, Written: 26.97 MiB
[DLManager] INFO:  - Cache usage: 35.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 11.24 MiB/s (raw) / 27.96 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 12.95 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 89.86% (3544/3944), Running for 00:00:03, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 29.26 MiB, Written: 67.98 MiB
[DLManager] INFO:  - Cache usage: 17.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 11.51 MiB/s (raw) / 23.99 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 40.99 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 90.42% (3566/3944), Running for 00:00:04, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 39.98 MiB, Written: 89.98 MiB
[DLManager] INFO:  - Cache usage: 17.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 10.71 MiB/s (raw) / 21.97 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 21.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 90.87% (3584/3944), Running for 00:00:05, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 49.59 MiB, Written: 107.98 MiB
[DLManager] INFO:  - Cache usage: 18.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 9.59 MiB/s (raw) / 18.97 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 17.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 91.56% (3611/3944), Running for 00:00:06, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 61.83 MiB, Written: 134.98 MiB
[DLManager] INFO:  - Cache usage: 17.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 12.22 MiB/s (raw) / 25.96 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 26.96 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 92.27% (3639/3944), Running for 00:00:07, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 72.75 MiB, Written: 153.98 MiB
[DLManager] INFO:  - Cache usage: 26.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 10.91 MiB/s (raw) / 27.96 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 18.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 94.57% (3730/3944), Running for 00:00:08, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 82.60 MiB, Written: 183.98 MiB
[DLManager] INFO:  - Cache usage: 22.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 9.84 MiB/s (raw) / 25.98 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 29.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 95.36% (3761/3944), Running for 00:00:09, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 93.22 MiB, Written: 213.98 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 10.60 MiB/s (raw) / 23.98 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 29.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 95.99% (3786/3944), Running for 00:00:10, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 104.32 MiB, Written: 238.98 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 11.09 MiB/s (raw) / 24.97 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 24.97 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 96.58% (3809/3944), Running for 00:00:11, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 115.34 MiB, Written: 261.98 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 11.01 MiB/s (raw) / 22.98 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 22.98 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 97.26% (3836/3944), Running for 00:00:12, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 126.77 MiB, Written: 288.98 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 16
[DLManager] INFO:  + Download	- 11.41 MiB/s (raw) / 26.96 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 26.96 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 98.33% (3878/3944), Running for 00:00:13, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 137.21 MiB, Written: 314.98 MiB
[DLManager] INFO:  - Cache usage: 16.00 MiB, active tasks: 14
[DLManager] INFO:  + Download	- 10.42 MiB/s (raw) / 27.96 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 25.96 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: = Progress: 100.00% (3944/3944), Running for 00:00:14, ETA: 00:00:00
[DLManager] INFO:  - Downloaded: 141.46 MiB, Written: 330.70 MiB
[DLManager] INFO:  - Cache usage: 0.00 MiB, active tasks: 0
[DLManager] INFO:  + Download	- 4.25 MiB/s (raw) / 13.99 MiB/s (decompressed)
[DLManager] INFO:  + Disk	- 15.71 MiB/s (write) / 0.00 MiB/s (read)
[DLManager] INFO: Waiting for installation to finish...
[DLManager] INFO: All done! Download manager quitting...
[cli] INFO: Finished downloading, setting up overlay...
Traceback (most recent call last):
  File "legendary/cli.py", line 3016, in <module>
  File "legendary/cli.py", line 2965, in main
  File "legendary/cli.py", line 2247, in manage_eos_overlay
  File "legendary/utils/eos.py", line 52, in query_registry_entries
ValueError: No user.reg file, invalid path
[130620] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce

1. Attempt to install the EOS overlay
2. Wait for the download to finish
3. See that legendary has crashed during installation

## Additional information

This was performed with a custom --prefix and --path, so that may be a contributing factor.
The same happens with the `enable` argument as well, returning
```
~ » /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay enable --prefix /mnt/games/heroic/Prefixes/FallGuys --path /mnt/games/heroic/.overlay -v
[cli] INFO: Using prefix "/mnt/games/heroic/Prefixes/FallGuys"
Traceback (most recent call last):
  File "legendary/cli.py", line 3016, in <module>
  File "legendary/cli.py", line 2965, in main
  File "legendary/cli.py", line 2169, in manage_eos_overlay
  File "legendary/utils/eos.py", line 52, in query_registry_entries
ValueError: No user.reg file, invalid path
[164686] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by CommandMC** [comment]
Are you using Proton by any chance?

**Comment by furokku** [comment]
Using proton-ge, yes.

**Comment by CommandMC** [comment]
You will have to add a `/pfx` to your prefix path then

**Comment by furokku** [comment]
Well, there already is one.
```
~ » ls /mnt/games/heroic/Prefixes/FallGuys
config_info  pfx  pfx.lock  tracked_files  version
~ » ls /mnt/games/heroic/Prefixes/FallGuys/pfx
dosdevices  drive_c  system.reg  userdef.reg  user.reg
```

**Comment by furokku** [comment]
Ah, that explains it. Seems to work now, thank you very much for the quick response!
