### ISSUE TITLE
Failed to execute script 'cli' due to unhandled exception!

### ISSUE THREAD

**Issue by ZombieCuber** [derrod/legendary#443]
## Platform

Operating system and version: linux mint
Legendary version (`legendary -V`):

## Current Behavior

./legendary eos-overlay enable --prefix /home/$USER/Games/Heroic/Prefixes/FallGuys/pfx
[cli] INFO: Using prefix "/home/zc/Games/Heroic/Prefixes/FallGuys/pfx"
Traceback (most recent call last):
  File "legendary/cli.py", line 3016, in <module>
  File "legendary/cli.py", line 2965, in main
  File "legendary/cli.py", line 2169, in manage_eos_overlay
  File "legendary/utils/eos.py", line 52, in query_registry_entries
ValueError: No user.reg file, invalid path
[43720] Failed to execute script 'cli' due to unhandled exception!

## Steps to Reproduce

1.
2.
3.
4.

**Comment by derrod** [comment]
The prefix needs to be initialised (e.g. via `wineboot`), otherwise this will not work.
