### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by Pcodcsja** [derrod/legendary#467]
C:\Users\JYhou\Downloads>legendary list
[cli] INFO: Logging in...
Traceback (most recent call last):
  File "legendary\cli.py", line 3053, in <module>
  File "legendary\cli.py", line 2964, in main
  File "legendary\cli.py", line 190, in list_games
  File "legendary\core.py", line 178, in login
ValueError: No saved credentials
[17824] Failed to execute script 'cli' due to unhandled exception!

windows 10 x64    python 3.9

**Comment by nutterthanos** [comment]
You need to run legendary auth
And paste the SID into the command line and press enter
Shouldn't have any problems afterwards

**Comment by nutterthanos** [comment]
also this might be in the FAQ when that gets created
