### ISSUE TITLE
[WinError5: Access denied]

### ISSUE THREAD

**Issue by Andipog2** [derrod/legendary#483]
## Platform

Operating system and version: Windows 11 22H2
Legendary version (`legendary -V`): 20.29

## Expected Behavior

I write any commad, and it does it
## Current Behavior

E:\Games>legendary auth
Traceback (most recent call last):
  File "legendary\cli.py", line 3054, in <module>
  File "legendary\cli.py", line 2937, in main
  File "legendary\cli.py", line 43, in __init__
  File "legendary\core.py", line 63, in __init__
  File "legendary\lfs\lgndry.py", line 57, in __init__
  File "os.py", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\username/.config/legendary\\manifests'
[13156] Failed to execute script 'cli' due to unhandled exception!
## Steps to Reproduce

I don't think it happens to anyone else tbh
1. Open legendary.exe
2. write a command: e.g legendary auth
3. get error

## Additional information

I have python 3.10.7 installed
![image_2022-10-01_191418094](https://user-images.githubusercontent.com/114339282/193422706-455615bf-3d5d-4815-8e48-257109a931a6.png)

**Comment by nutterthanos** [comment]
um your permissions must be messed up
