### ISSUE TITLE
Error using egl-sync on a fresh install

### ISSUE THREAD

**Issue by djibux** [derrod/legendary#50]
With a fresh install, egl-sync crashes:
```
$ legendary egl-sync
EGL path not found, please manually provide the path to the WINE prefix it is installed in
Path [empty input to quit]: /home/djib/epic-games-store
Traceback (most recent call last):
  File "/home/djib/.local/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/home/djib/.local/lib/python3.8/site-packages/legendary/cli.py", line 1101, in main
    cli.egs_sync(args)
  File "/home/djib/.local/lib/python3.8/site-packages/legendary/cli.py", line 797, in egs_sync
    self.core.lgd.config.set('Legendary', 'egl_programdata', egl_path)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Legendary'
```

To solve the issue I added an empty `[Legendary]` section in `~/.config/legendary/config.ini`.

**Comment by derrod** [comment]
Thanks, I'll fix it in another bugfix release later today.
