### ISSUE TITLE
Python error when downloading DLC content

### ISSUE THREAD

**Issue by declanmarks** [derrod/legendary#51]
I was downloading Civilisation VI which completed successfully, but was then asked if I wanted to download the DLC content, I selected yes. I then recieved the following error:

```
The following DLCs are available for this game:
 - Civilization VI : Aztec DLC (App name: KingletAztec, version: 1.0.1.504666c)
Manually installing DLCs works the same; just use the DLC app name instead.
Do you wish to automatically install DLCs ? [Y/n]: y
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Install candidate is DLC
[cli] INFO: Preparing download...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.14', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/cli.py", line 947, in main
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/cli.py", line 565, in install_game
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/cli.py", line 464, in install_game
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/core.py", line 611, in prepare_download
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/core.py", line 558, in get_cdn_manifest
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
```

Just like the error suggested I tried installed the DLC after which worked successfully.

**Comment by derrod** [comment]
That error indicates that the connection to the Epic API was interrupted for some reason. Currently there's no error handling or retries for that (only for game chunk downloads) but that's on my ToDo list.
