### ISSUE TITLE
Failed to execute script 'cli' due to unhandled exception!

### ISSUE THREAD

**Issue by PKPenguin321** [derrod/legendary#512]
## Platform

Operating system and version: Windows 10 Home N 22H2
Legendary version (`legendary -V`): Dark Energy (hotfix 5)

## Expected Behavior
Legendary will run without errors. It used to do this and has worked for months up until yesterday, and as of today it fails with no apparent cause.

## Current Behavior

![image](https://user-images.githubusercontent.com/8345184/207508212-b9b47698-023b-4887-8c2f-e3d5a1e61375.png)

## Steps to Reproduce

1. Run legendary at all. Install, launch, update, etc. all fail with the same error
2.
3.
4.

## Additional information

As mentioned, Legendary has worked for months with no errors until today with no apparent cause. I am fairly certain this is on my end but have no idea what to do to fix it. Reinstalling Legendary and running previous versions does not resolve the issue.

**Comment by PKPenguin321** [comment]
With --debug flag:
```legendary --debug launch Fortnite
[cli] INFO: Logging in...
[LGDLFS] DEBUG: Failed to load overlay install data: FileNotFoundError(2, 'No such file or directory')
[Core] INFO: Logging in...
Traceback (most recent call last):
  File "legendary\cli.py", line 3069, in <module>
  File "legendary\cli.py", line 2984, in main
  File "legendary\cli.py", line 600, in launch_game
  File "legendary\core.py", line 236, in login
  File "legendary\api\egs.py", line 128, in start_session
KeyError: 'access_token'
[8828] Failed to execute script 'cli' due to unhandled exception!```

**Comment by derrod** [comment]
@user4302 @PKPenguin321 @BoredmanDA Please let me know what the latest CI build reports in this case: https://github.com/derrod/legendary/actions/runs/3687109577

This is due to epic now requiring you to add a date of birth to your account. And they didn't have the decency to actually report an error in that case.

**Comment by user4302** [comment]
> @user4302 @PKPenguin321 @BoredmanDA Please let me know what the latest CI build reports in this case: https://github.com/derrod/legendary/actions/runs/3687109577
> 
> This is due to epic now requiring you to add a date of birth to your account. And they didn't have the decency to actually report an error in that case.

I think they all passed?
Also I did run the repo locally in a venv and I do not get the issue in that case.

**Comment by BoredmanDA** [comment]
> @user4302 @PKPenguin321 @BoredmanDA Please let me know what the latest CI build reports in this case: https://github.com/derrod/legendary/suites/9842655225/artifacts/474321471
> 
> This is due to epic now requiring you to add a date of birth to your account. And they didn't have the decency to actually report an error in that case.

So far so good! After running `auth` again to update the login credentials, `list` and `install` seem to be working like a charm again.
It did, however, throw an exception after running `auth`:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
```
but it doesn't seem like there's any other issues running all the other commands afterwards.
Haven't tested `launch` yet but I can assume it's been fixed as well, considering all the other commands that require logging in are working again.
