### ISSUE TITLE
rocket league doesnt run.

### ISSUE THREAD

**Issue by JamesHasACat** [derrod/legendary#534]
## version of os and legendary

macos 12.5
legendary version "0.20.32", codename "Dark Energy (hotfix #6)"
## Expected Behavior

rocket league should launch

## Current Behavior

./legendary launch rocket league                                                                  ✔  base   20:35:12  
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
Traceback (most recent call last):
  File "legendary/cli.py", line 3061, in <module>
  File "legendary/cli.py", line 2976, in main
  File "legendary/cli.py", line 608, in launch_game
  File "legendary/core.py", line 701, in get_launch_parameters
  File "legendary/core.py", line 633, in get_app_launch_command
IndexError: list index out of range
[36195] Failed to execute script 'cli' due to unhandled exception!

## Steps to Reproduce
1.goto terminal
2../legendary launch rocket league

## Additional information

i am on an arm mac

**Comment by CommandMC** [comment]
https://github.com/derrod/legendary/blob/ae05b4c1e5c12b64caed76317f9f104e55ab0da7/legendary/core.py#L633

Seems like you don't have CrossOver installed

**Comment by JamesHasACat** [comment]
> https://github.com/derrod/legendary/blob/ae05b4c1e5c12b64caed76317f9f104e55ab0da7/legendary/core.py#L633
> 
> Seems like you don't have CrossOver installed

do i need to download the console version of crossover?

**Comment by CommandMC** [comment]
@JamesHasACat You need the CrossOver application (https://www.codeweavers.com/crossover#mac)
@alexanderanchishkin Rocket League does not have a native MacOS version, you will need some kind of compatibility layer to run the game. If you have something other than CX installed, disable automatic CX detection by adding `disable_auto_crossover = true` to Legendary's config file

**Comment by alexanderanchishkin** [comment]
> disable automatic CX detection by adding `disable_auto_crossover = true` to Legendary's config file

@CommandMC Thanks a lot! I understand about compatibility layer for running the game. But I use Heroic Game Launcher and it suggests run not only through CrossOver app but also through wine-crossover. Moreover you can use Game Porting Toolkit in macOS Sonoma (now it's only beta). So I really don't need CrossOver for running RocketLeague.

Next steps resolved my issue (I think OP's too if another wine was used):
1. Open `~/.config/legendary/config.ini`
2. Add under [legendary]:
`disable_auto_crossover = true`
