### ISSUE TITLE
Legendary don't work suddenly

### ISSUE THREAD

**Issue by Pcodcsja** [derrod/legendary#545]
**After I use “Legendary auth“ and it output these:**
Traceback (most recent call last):
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\site-packages\legendary\cli.py", line 2970, in main
    cli.auth(args)
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\site-packages\legendary\cli.py", line 160, in auth
    tmp = json.loads(auth_code)
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Pcodcsja\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Neither version 0.20.32 nor version 0.20.31 will work. Is there something wrong with my python environment?**

**Comment by nick123456789025** [comment]
I hate when questions like these get ignored. I would also like to know the answer. I'm dealing with the same problem

**Comment by CommandMC** [comment]
@Pcodcsja Whatever you gave Legendary as your auth code wasn't... an auth code (or valid JSON containing an auth code)

@nick123456789025 If you're truly getting the same issue, then that's your answer as well
