### ISSUE TITLE
Trying to install New Vegas without success on window 10

### ISSUE THREAD

**Issue by Trokinos** [derrod/legendary#562]
on window 10, trying to install Fallout: New Vegas
legendary.exe install 5daeb974a22a435988892319b3a4f476

```
Traceback (most recent call last):
  File "legendary\cli.py", line 3069, in <module>
  File "legendary\cli.py", line 2986, in main
  File "legendary\cli.py", line 944, in install_game
  File "legendary\core.py", line 1453, in prepare_download
  File "legendary\downloader\mp\manager.py", line 395, in run_analysis
MemoryError: Current shared memory cache is smaller than required: 2048.0 MiB < 4902.0 MiB. Try running legendary with "--enable-reordering" to reduce memory usage, or use "--max-shared-memory 4934" to increase the limit.
[8844] Failed to execute script 'cli' due to unhandled exception!
```

then with legendary.exe install 5daeb974a22a435988892319b3a4f476 --max-shared-memory 4934
i got further this time, but :

```
Do you wish to install "Fallout: New Vegas"? [Y/n]: Y
[DLManager] INFO: Download Manager running with process-id: 8044
Process DLManager:
Traceback (most recent call last):
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\downloader\mp\manager.py", line 588, in run
    self.run_real()
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\downloader\mp\manager.py", line 622, in run_real
    self.shared_memory = SharedMemory(create=True, size=self.max_shared_memory)
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\multiprocessing\shared_memory.py", line 151, in __init__
    self._mmap = mmap.mmap(-1, size, tagname=temp_name)
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service

```

Tried with legendary.exe install 5daeb974a22a435988892319b3a4f476 --enable-reordering
and this time i got :
```
Traceback (most recent call last):
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 2978, in main
    cli.install_game(args)
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\cli.py", line 936, in install_game
    dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\core.py", line 1453, in prepare_download
    anlres = dlm.run_analysis(manifest=new_manifest, old_manifest=old_manifest,
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\downloader\mp\manager.py", line 395, in run_analysis
    raise MemoryError(f'Current shared memory cache is smaller than required: {shared_mib} < {required_mib}. '
MemoryError: Current shared memory cache is smaller than required: 2048.0 MiB < 4913.0 MiB. Try running legendary with "--enable-reordering --max-shared-memory 4945"
```

Finally tried with legendary.exe install 5daeb974a22a435988892319b3a4f476 --enable-reordering --max-shared-memory 4945
and back to
```
Traceback (most recent call last):
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\downloader\mp\manager.py", line 588, in run
    self.run_real()
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\site-packages\legendary\downloader\mp\manager.py", line 622, in run_real
    self.shared_memory = SharedMemory(create=True, size=self.max_shared_memory)
  File "C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\lib\multiprocessing\shared_memory.py", line 151, in __init__
    self._mmap = mmap.mmap(-1, size, tagname=temp_name)
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service
```

I'm rather puzzled i must say, as i have installed so far all the freebie i wanted, The one i remember that required an added --max-shared-memory ( it was for my case --max-shared-memory 3248 ) was Bioshock Infinite and it installed
Also very odd that everytime the "required" memory cache is not the same number ?

**Comment by CommandMC** [comment]
> OSError: [WinError 1450] Insufficient system resources exist to complete the requested service

Looks like you just don't have enough free RAM for Legendary to allocate its cache

**Comment by Trokinos** [comment]
Looks like it was it, after closing every program and my browser (as on my 8gb of RAM window10+various things were eating 40% of it), i managed to get New Vegas downloaded (of course without the DLC as there's the tab in file name that screw up on window 10) with  
`legendary.exe install 5daeb974a22a435988892319b3a4f476 --max-shared-memory 4934`
  
But wondering why that game requires such a huge cache when some games with much bigger install size (The Hunter Call of the Wild) by example) do not.

**Comment by loathingKernel** [comment]
> But wondering why that game requires such a huge cache when some games with much bigger install size (The Hunter Call of the Wild) by example) do not.

I assume it has to do with the size of individual files rather the game as a whole. Larger files need more cache to be reconstructed.

**Comment by Trokinos** [comment]
> > But wondering why that game requires such a huge cache when some games with much bigger install size (The Hunter Call of the Wild) by example) do not.
> 
> I assume it has to do with the size of individual files rather the game as a whole. Larger files need more cache to be reconstructed.

Ah thanks for the precision, that makes sense.

**Comment by derrod** [comment]
In this case it's because of deduplication. They essentially upload five copies of the game, one for each langauge. Obviously there's going to be a lot of overlap there so Legendary uses its cache to reuse the data that is shared across versions.

**Comment by Trokinos** [comment]
They did the same with Fallout 3 too (i think it's because they used the gamepass/microsoft store version instead the version everyone else was using) , it came with duplicated game (one for every language supported even if you didn't used them)
