### ISSUE TITLE
After updating to 0.20.33 on scoop, can't open legendary anymore

### ISSUE THREAD

**Issue by i-report-bugs** [derrod/legendary#571]
## Platform

Operating system and version: Windows 10 64 bit
Legendary version (`legendary -V`): I can't provide this because legendary doesn't open

## Expected Behavior

It should work how it did before.

## Current Behavior

When I launch legendary, with or without flags, it now shows this

Traceback (most recent call last):
  File "legendary\cli.py", line 21, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "legendary\core.py", line 26, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "legendary\lfs\lgndry.py", line 12, in <module>
ModuleNotFoundError: No module named 'filelock'
[14796] Failed to execute script 'cli' due to unhandled exception!

## Steps to Reproduce

1. Open cmd
2. Type legendary and press enter

## Additional information

It used to work without any issues whatsoever, then when I updated legendary (I use scoop package manager), it showed that error above

**Comment by Doc-4** [comment]
This is the same case with mine installed manually, I think this is a general bug with the new release

**Comment by derrod** [comment]
Download the new Windows exe from https://github.com/derrod/legendary/releases/tag/0.20.33
