### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character

### ISSUE THREAD

**Issue by Renari** [derrod/legendary#614]
## Platform

Operating system and version: Windows 11
Legendary version (`legendary -V`): 0.20.32

## Expected Behavior
Legendary lists games correctly.

## Current Behavior

Legendary throws an error when list_games is called.

## Steps to Reproduce

1. Login to EPIC with Legendary
2. Call list_games

## Additional information

<details><summary>Click to expand log</summary>

```
An error has occurred! Try to Logout and Login on your Epic account.
Available games:
* ARK: Survival Evolved (App name: aafc587fbf654758802c8e41e4fb3255 | Version: 358.17.win)
* BioShock 2 Remastered (App name: b22ce34b4ce0408c97a888554447479b | Version: 1.0.0_BN-138_CL-17677)
* BioShock Infinite: Complete Edition (App name: f9d6f0530ea140909f8e8a997a7532d7 | Version: 1.0.0_BN-314_CL-17899)
* BioShock Remastered (App name: bc2c95c6ff564a16b26644f1d3ac3c55 | Version: 1.0.0_BN-187_CL-17677)
* Brothers - A Tale of Two Sons (App name: Tamarind | Version: 1.1)
* Cave Story+ (App name: 1dea8a6ddb544842a58e4b5c8675ff58 | Version: 1.1)
* Celeste (App name: Salt | Version: 1.4.0.0-Windows)
* Cities Skylines (App name: bcbc03d8812a44c18f41cf7d5f849265 | Version: 1.17.1-f4-fixed)
* Control (App name: Calluna | Version: 01.13)
* Cris Tales (App name: e7d92786abe54fae9319c1ddb94ae271 | Version: 1.0.7)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>File "legendary\cli.py", line 2980, in main
File "legendary\cli.py", line 239, in list_games
UnicodeEncodeError: 'cp932' codec can't encode character '\xae' in position 18: illegal multibyte sequence
[592936] Failed to execute script 'cli' due to unhandled exception!
```

</details>

Appears to be similar to this issue: https://github.com/derrod/legendary/issues/297

**Comment by CommandMC** [comment]
This is resolved in 0.20.33

To use it in Heroic, download the EXE file and specify the path to it in the "Advanced Settings"
Note that it'll have [other issues](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2806)
