### ISSUE TITLE
egl-sync: EGS ProgramData path does not exist

### ISSUE THREAD

**Issue by Lasa2** [derrod/legendary#623]
The egl-sync command fails if you never installed a game via the EGL. The EGL does not create the Manifests Directory by default.

## Platform

Operating system and version: Windows 11 Pro Build 22621.2134
Legendary version (`legendary -V`): Legendary v0.20.33 - "Undue Alarm"

## Expected Behavior
legendary egl-sync should sync the installed games to EGL

## Current Behavior
legendary is unable to sync installed games due to:

Traceback (most recent call last):
  File "legendary\cli.py", line 3137, in <module>
  File "legendary\cli.py", line 3072, in main
  File "legendary\cli.py", line 1510, in egs_sync
  File "legendary\core.py", line 1766, in egl_get_exportable
  File "legendary\core.py", line 560, in get_installed_list
  File "legendary\core.py", line 1933, in egl_sync
  File "legendary\core.py", line 1883, in egl_restore_or_uninstall
  File "legendary\core.py", line 1860, in egl_export
  File "legendary\lfs\egl.py", line 85, in set_manifest
ValueError: EGS ProgramData path does not exist
[15796] Failed to execute script 'cli' due to unhandled exception!

## Steps to Reproduce

1. install the Epic Games Launcher e.g. by winget install EpicGames.EpicGamesLauncher
2. login into the Epic Games Launcher
3. complete legendary auth
4. install any game via legendary install
5. run legendary egl-sync

## Additional information

I could fix the crash by manually creating the "Manifests" Directory in "C:\ProgramData\Epic\EpicGamesLauncher\Data"

**Comment by Lasa2** [comment]
I just saw that this is collides a bit with https://github.com/derrod/legendary/pull/421, so maybe it a good idea to ask if legendary should create the missing dir or disable the egl-sync, as its uncertain if the EGL got uninstalled or just no game got installed via the EGL.

**Comment by laurencei** [comment]
I just had this issue now.

"This crash is resolvable by either creating the Manifests directory by hand or install a game via EGL."
@Lasa2  - where exactly did you create the Manifest directory?

**Comment by Lasa2** [comment]
Under %PROGRAMDATA%\Epic\EpicGamesLauncher\Data\
so that %PROGRAMDATA%\Epic\EpicGamesLauncher\Data\Manifests is a valid path

**Comment by Lasa2** [comment]
egl_programmdata is only used on non windows machines https://github.com/derrod/legendary/blob/7fefdc497329276fc8c41d20e72600e0112352d1/legendary/core.py#L64-L72

on windows the directory is hardcoded https://github.com/derrod/legendary/blob/7fefdc497329276fc8c41d20e72600e0112352d1/legendary/lfs/egl.py#L18-L24

**Comment by dmeza85** [comment]
Issue is still present on Windows 11 26H2; had to manually create the %PROGRAMDATA%\Epic\EpicGamesLauncher\Data\Manifests folder and after doing that my errors cleared

Playnite portable v10.56
Legendary plugin 1.15.0
