### ISSUE TITLE
Epic Games formerly listed by Legendary now delisted?

### ISSUE THREAD

**Issue by Darthagnon** [derrod/legendary#633]
## Platform

Operating system and version: Win10
Legendary version (`legendary -V`): `legendary version "0.20.34", codename "Direct Intervention"`

## Expected Behavior
I've been keeping a list of my games claimed on Epic [here](https://github.com/Darthagnon/my-epic-games), where I use Legendary's listing functions to export a list every couple of months.

## Current Behavior
I recently updated Legendary, as I noticed an update prompt when I had to re-auth. I generated new lists with the latest Christmas 2023 giveaways from Epic, and [updated my Epic Games list repo](https://github.com/Darthagnon/my-epic-games/commit/16128491d3e609a1ad1473e155a4fc4c1c27ca03). I noticed that a whole bunch of games are now missing from the list. A few I checked still seem to appear on the EGS as "In Library", but I was wondering what might be causing them to disappear from the list like this? Is it a bug in Legendary or some install behaviour changed?

## Steps to Reproduce

1. Run `legendary list-games --csv >> epic-games.csv | legendary list-games >> epic-games.txt` with the latest version of Legendary
2. If you compare your new lists with previously generated lists, you will notice some games missing. They are not removed from the EGS account, delisted from the store or updated in any major way.

**Comment by derrod** [comment]
I do have a number of these games and they show up normally for me, so I don't really know what would be happening there.

**Comment by Darthagnon** [comment]
I don't know if this might be relevant, but when I'm using [the commands via BAT file as usual](https://github.com/Darthagnon/my-epic-games/blob/master/print-csv-of-your-games.bat), it prints a weird `1` in the console log (screenshot attached) and counts the games wrong.
![cmd_qnofIe4LP0](https://github.com/derrod/legendary/assets/20792748/b4925349-5289-4847-9b93-afdf9cf64120)

**Comment by Darthagnon** [comment]
This still seems to be an issue, and now I'm getting the following errors when I try and run the list to file commands:
```
E:\Program Files\Games\legendary>legendary list-games --csv >> epic-games.csv
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
[Core] INFO: Fetching metadata for 2 app(s).
Traceback (most recent call last):
  File "legendary\cli.py", line 3149, in <module>
  File "legendary\cli.py", line 3060, in main
  File "legendary\cli.py", line 200, in list_games
  File "legendary\core.py", line 476, in get_game_and_dlc_list
  File "legendary\core.py", line 449, in fetch_game_meta
TypeError: 'NoneType' object is not subscriptable
[10384] Failed to execute script 'cli' due to unhandled exception!

E:\Program Files\Games\legendary>legendary list-games >> epic-games.txt
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Getting game list... (this may take a while)
[Core] INFO: Fetching metadata for 2 app(s).
Traceback (most recent call last):
  File "legendary\cli.py", line 3149, in <module>
  File "legendary\cli.py", line 3060, in main
  File "legendary\cli.py", line 200, in list_games
  File "legendary\core.py", line 476, in get_game_and_dlc_list
  File "legendary\core.py", line 449, in fetch_game_meta
TypeError: 'NoneType' object is not subscriptable
[13512] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by derrod** [comment]
This happened to me as well now with a game that has been removed from the store, deleting the `assets.json` file in your config directory may fix it.

**Comment by user4302** [comment]
> This happened to me as well now with a game that has been removed from the store, deleting the `assets.json` file in your config directory may fix it.

this worked for me,
i am now able to list all the games instead of "1" game
and i am also able to import a specific game that wasnt importing before

**Comment by Darthagnon** [comment]
Accidentally commited a secret to my epic games list repo; I have removed it with [bfg](https://rtyley.github.io/bfg-repo-cleaner/), but the historical commit still seems to be cached by Github, despite my rewriting history to remove it.
