### ISSUE TITLE
NoneType result on path for sync-saves

### ISSUE THREAD

**Issue by instinctualjealousy** [derrod/legendary#657]
## Platform

Operating system and version:
Windows 10 22H2 64-bit

Legendary version (`legendary -V`):
legendary version "0.20.34", codename "Direct Intervention"

## Expected Behavior

Successfully upload saves for cloud-supported games.

## Current Behavior

Due to either an environment-specific issue caused by me, clashing dependency versions, or simply a bug in legendary, this happens:
```
C:\Users\Adam>legendary sync-saves
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Got 24 remote save game(s)
[cli] INFO: Checking "art of rally" (01805192c8074820b1257fcfd97f2648)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Adam\scoop\apps\python\current\Scripts\legendary.exe\__main__.py", line 7, in <module>
  File "C:\Users\Adam\scoop\apps\python\current\Lib\site-packages\legendary\cli.py", line 3076, in main
    cli.sync_saves(args)
  File "C:\Users\Adam\scoop\apps\python\current\Lib\site-packages\legendary\cli.py", line 518, in sync_saves
    res, (dt_l, dt_r) = self.core.check_savegame_state(igame.save_path, latest_save.get(igame.app_name))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adam\scoop\apps\python\current\Lib\site-packages\legendary\core.py", line 934, in check_savegame_state
    for _dir, _, _files in os.walk(path):
  File "<frozen os>", line 348, in walk
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Steps to Reproduce

Sadly, I can't think of any applicable steps.

## Additional information

This affects all games- this used to work for me splendidly, on this version, for many months. I noticed it while using Playnite, but I pulled down to operating it directly on CLI to see what mess it would inevitably spit out. I do keep my Python packages up to date, so some sort of version clash on dependencies might not be out of the question. I have done things that may have broken configuration at some point and not realized it. This might be less of a bug report and more of an unpaid support request at this rate... maybe a path is now wrong in one of the configuration files?

It's also worth noting that I installed the game in the log today.

**Comment by instinctualjealousy** [comment]
Issue randomly resolved itself without any updates. Decided to run sync-saves from the prompt and it was able to resolve all pending. Weird!
