### ISSUE TITLE
Legendary auth fails SSL verification

### ISSUE THREAD

**Issue by brondibur** [derrod/legendary#667]
## Platform

Operating system and version: Windows 11 Home 23H2 (22631.4317)
Legendary version (`legendary -V`): 0.20.34

## Expected Behavior

`legendary auth` should allow us to complete authentication

## Current Behavior

`legendary auth` fails with the following error:
```
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 700, in urlopen
  File "urllib3\connectionpool.py", line 994, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "legendary\cli.py", line 3149, in <module>
  File "legendary\cli.py", line 3058, in main
  File "legendary\cli.py", line 92, in auth
  File "legendary\core.py", line 272, in check_for_updates
  File "legendary\api\lgd.py", line 21, in get_version_information
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[4248] Failed to execute script 'cli' due to unhandled exception!
```

## Steps to Reproduce

1. Download legendary.exe and add it's location to the PATH
2. Run `legendary auth` in Powershell

## Additional information

The computer doesn't have Python installed

**Comment by brondibur** [comment]
This was happening due to GoGuardian enforced proxy settings. I think we should still have the option to bypass SSL verification, but closing this since it is not a bug.
