### ISSUE TITLE
Installation always fails on Windows 10

### ISSUE THREAD

**Issue by rorj** [derrod/legendary#67]
Get the same error every time I try to install any game.

Here's my config:
```ini
[Legendary]
locale = en-US
install_dir = D:\Epic Games
```

Output:
```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: D:\Epic Games\WorldOfGoo
[cli] INFO: Install size: 190.30 MiB
[cli] INFO: Download size: 183.45 MiB (Compression savings: 4.0%)
[cli] INFO: Reusable size: 0.00 MiB (chunks) / 0.00 MiB (unchanged)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.
Do you wish to install "World of Goo"? [Y/n]:
[DLManager] INFO: Download Manager running with process-id: 1416
[DLManager] INFO: Starting download workers...
Process DLManager:
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files (x86)\python38-32\lib\site-packages\legendary\downloader\manager.py", line 572, in run
    self.run_real()
  File "c:\program files (x86)\python38-32\lib\site-packages\legendary\downloader\manager.py", line 619, in run_real
    w = DLWorker(f'DLWorker {i + 1}', self.dl_worker_queue, self.dl_result_q,
  File "c:\program files (x86)\python38-32\lib\site-packages\legendary\downloader\workers.py", line 28, in __init__
    self.shm = SharedMemory(name=shm)
  File "c:\program files (x86)\python38-32\lib\multiprocessing\shared_memory.py", line 164, in __init__
    p_buf = _winapi.MapViewOfFile(
OSError: [WinError 8] Not enough memory resources are available to process this command
[cli] INFO: Finished installation process in 0.16 seconds.
```

**Comment by gibbed** [comment]
You're using 32-bit Python.

Requirements list:
> python 3.8+ (64-bit on Windows)
