### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Ayanashi** [derrod/legendary#678]
cannot login via legendary and heroic-games-launcher

_output >>_

```
`legendary auth
[cli] INFO: Testing existing login data if present...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x76e7eeeb9670>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x76e7eeeb9670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/legendary", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/legendary/cli.py", line 3058, in main
    cli.auth(args)
  File "/usr/lib/python3.12/site-packages/legendary/cli.py", line 92, in auth
    self.core.check_for_updates(force=True)
  File "/usr/lib/python3.12/site-packages/legendary/core.py", line 272, in check_for_updates
    version_info = self.lgdapi.get_version_information()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/legendary/api/lgd.py", line 21, in get_version_information
    r = self.session.get(f'https://{self._api_host}/v1/version.json',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x76e7eeeb9670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`

```
**Archlinux : 6.12-1
Legendary : 0.20.34 
urlib3 is already installed : 1.26.20-3 (aur)
python3: 3.12.7**
____

Login via HeroicGamesLauncher still load via epicgames login
![captura-2024-11-18-1731951257](https://github.com/user-attachments/assets/23b7da7c-b61c-4ec9-a3f6-99ef8450dc32)

Logina via HeroicGamesLauncher epic games alternative mode
![captura-2024-11-25-1732493909](https://github.com/user-attachments/assets/345dd693-821c-4a01-89f4-4c48a0beb839)

```
An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Testing existing login data if present...Traceback (most recent call last):
File "urllib3/connection.py", line 199, in _new_connFile "urllib3/util/connection.py", line 85, in create_connection
File "urllib3/util/connection.py", line 73, in create_connection
OSError: [Errno 101] Network is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "urllib3/connectionpool.py", line 789, in urlopen
File "urllib3/connectionpool.py", line 490, in _make_request
File "urllib3/connectionpool.py", line 466, in _make_request
File "urllib3/connectionpool.py", line 1095, in _validate_conn
File "urllib3/connection.py", line 693, in connect
File "urllib3/connection.py", line 214, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7d579abb5880>: Failed to establish a new connection: [Errno 101] Network is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "requests/adapters.py", line 667, in send
File "urllib3/connectionpool.py", line 843, in urlopen
File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d579abb5880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "legendary/cli.py", line 3224, in <module>
File "legendary/cli.py", line 3131, in mainFile "legendary/cli.py", line 93, in auth
File "legendary/core.py", line 274, in check_for_updates
File "legendary/api/lgd.py", line 21, in get_version_information
File "requests/sessions.py", line 602, in get
File "requests/sessions.py", line 589, in request
File "requests/sessions.py", line 703, in sendFile "requests/adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.legendary.gl', port=443): Max retries exceeded with url: /v1/version.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d579abb5880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[PYI-105589:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by derrod** [comment]
Seemslike there's something seriously wrong with your network configuration so this isn't a legendary issue.

**Comment by Ayanashi** [comment]
no tips or test? cause idk why id do this before i did't have any problems (past versions)

**Comment by Ayanashi** [comment]
#[same issue from](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4099#issue-2637405247)
i don't have any firewall rules set on so..i really don't understand

**Comment by Ayanashi** [comment]
im tryed istead connect via curl and ping on https://api.legendary.gl and cannot reach connection on port 443

**Comment by Ayanashi** [comment]
i disabled ipv6 and should not work again check again iptables rules or internal isp firewall and nothing strange the net work great with other domains or services on 443

**Comment by Ayanashi** [comment]
idk how but the previusly issue is gone and now i can login with legendary successfully!
